package cl.track.tec.test.four.exception;

public class DatetimeNotFoundException extends RuntimeException {
}
